### ISSUE TITLE
Update connection and cursor management

### ISSUE THREAD

**Issue by kenddly** [itudb2314/itudb2314#2]
Update connection and cursor management for database using the syntax given in the lecture slides 6.

**Comment by kenddly** [comment]
Should modify connect method for database class to return connection or cursor. Disconnect should take a connection or cursor object to disconnect from the database. Connection object should be removed from database class.
Connection should rollback changes made to the database in case of an error.

An example CRUD function:

```python
def get(db:db): ->
    try:
        connection = db.get_connection()
        cursor = connection.cursor()
        ............................
        cursor.commit()

    except Exception as e:
        connection.rollback()

    finally:
        connection.close()
```

**Comment by AbdullahSh20** [comment]
did the changes in main.py, db.py, and my previous 2 tables and pushed the last one too

**Comment by AbdullahSh20** [comment]
I think this issue is done
